OLLAMA_MODEL = "sqlcoder:latest"
OLLAMA_BASE_URL = "http://localhost:11434"
DB_URL = "postgresql+psycopg2://postgres:postgres123@localhost:5433/db_agent"
QDRANT_URL = "http://localhost:6333"
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
